name: CI Pipeline For Flusk App
run-name: CI Pipeline For Flusk App

on:
  push:
    paths:
      - 'app/**'

jobs:
  setup-kind-cluster:
    runs-on: self-hosted

    steps:
      # Step 1: Clone Repository
      - name: Clone Repository Files
        uses: actions/checkout@v3

      # Step 2: Login to docker
      - run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      # LOGS:
      - run: pwd
      - run: ls

      # Step 3: Build docker image
      - run: cd app
      - run: sudo docker build -t eyalcohenhaver/technionfinalproject .

      # LOGS:
      - run: pwd
      - run: ls

      # Step 4: Push docker image
      - run: sudo docker push eyalcohenhaver/technionfinalproject
