name: CI Pipeline For Flusk App
run-name: CI Pipeline For Flusk App

on:
  push:
    paths:
      - 'app/**'

jobs:
  setup-kind-cluster:
    runs-on: self-hosted

    steps:
      # Step 1: Clone Repository
      - name: Clone Repository Files
        uses: actions/checkout@v3

      # Step 2: Login to docker
#      - run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
      - run: docker login --username mellvinch@gmail.com --password 5H-Bt2TP8VD7e4,
      - run: sudo docker build -t eyalcohenhaver/technionfinalproject ./app

      # Step 4: Push docker image
      - run: sudo docker push eyalcohenhaver/technionfinalproject:latest
