name: Setup CICD EC2 runner
run-name: Deploying EC2 Runner on ${{ inputs.EC2_IP }}

on:
  workflow_dispatch:
    inputs:
      EC2_IP:
        description: "The CICD EC2 instance IP"
        required: true

jobs:
  setup-kind-cluster:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Clone Repository
      - name: Clone Repository Files
        uses: actions/checkout@v3

      # Step 2: SSH to EC2 and Install Kind + Dependencies
      - name: Connect and setup ec2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ inputs.EC2_IP }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            sudo yum update -y
            sudo yum install -y docker
            sudo systemctl enable docker
            sudo systemctl start docker
            sudo yum install -y yum-utils
            sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
            sudo yum -y install terraform


            mkdir actions-runner && cd actions-runner
            curl -o actions-runner-linux-x64-2.321.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.321.0/actions-runner-linux-x64-2.321.0.tar.gz
            sudo yum install -y perl-Digest-SHA
            echo "ba46ba7ce3a4d7236b16fbe44419fb453bc08f866b24f04d549ec89f1722a29e  actions-runner-linux-x64-2.321.0.tar.gz" | shasum -a 256 -c
            tar xzf ./actions-runner-linux-x64-2.321.0.tar.gz
            sudo yum install -y libicu
            sudo -u ec2-user ./config.sh --url https://github.com/EyalCohenHaver/technionfinalproject --token ${{ secrets.GIT_RUNNER_TOKEN }}

      run: ssh -i ${{ secrets.SSH_KEY }} ${{ inputs.EC2_IP }}@ec2-user -f 'sudo -u ec2-user ./run.sh'