name: CD Terraform Pipeline
run-name: CD Terraform Pipeline

on:
  push:
    paths:
      - 'terraform/**'
      - '!terraform/menual.tf'

jobs:
  CD Terraform Pipeline:
    runs-on: self-hosted

    steps:
      # Step 1: Clone Repository
      - name: Clone Repository Files
        uses: actions/checkout@v3

      #Step 2: Cradential setup
      - run: echo "${{ secrets.AWS_CREDENTIALS }}" > ~/.aws/credentials

      # Step 3: terraform init
      - run: cd terraform && sudo terraform init

      # Step 4: Push docker image
      - run: sudo terraform apply -auto-approve
